---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: traefik-cert-v3
  namespace: traefik
spec:
  domains:
  - api.victorgarciar.com
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: traefik-frontend-cfg-v3
  namespace: traefik
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress-v3
  namespace: traefik
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "traefik-http-lb"
    networking.gke.io/v1beta1.FrontendConfig: "traefik-frontend-cfg-v3"
    networking.gke.io/managed-certificates: "traefik-cert-v3"
spec:
  defaultBackend:
    service:
      name: traefik
      port:
        number: 80