---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  domains:
  - api.victorgarciar.com
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: traefik-frontend-cfg
  namespace: traefik
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "traefik-http-lb"
    networking.gke.io/v1beta1.FrontendConfig: "traefik-frontend-cfg"
    networking.gke.io/managed-certificates: "traefik"
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80